#include "cocotone_song_editor_basics.h"

//==============================================================================
#include "SongEditor/PianoRoll/cocotone_PianoRollColours.h"
#include "SongEditor/PianoRoll/cocotone_PianoRollPositionUtility.h"
#include "SongEditor/PianoRoll/cocotone_PianoRollKeyboard.h"
#include "SongEditor/PianoRoll/cocotone_PianoRollTimeRuler.h"
#include "SongEditor/PianoRoll/cocotone_PianoRollEventDispatcher.h"
#include "SongEditor/PianoRoll/cocotone_PianoRollPreviewSurface.h"
#include "SongEditor/PianoRoll/cocotone_PianoRollInteractionSurface.h"
#include "SongEditor/Transport/cocotone_BeatTimeUtility.h"
#include "SongEditor/Quantize/cocotone_QuantizeEngine.h"
#include "SongEditor/cocotone_SongEditorCommand.h"

//==============================================================================
#include "SongEditor/PianoRoll/cocotone_PianoRollKeyboard.cpp"
#include "SongEditor/PianoRoll/cocotone_PianoRollTimeRuler.cpp"
#include "SongEditor/PianoRoll/cocotone_PianoRollEventDispatcher.cpp"
#include "SongEditor/PianoRoll/cocotone_PianoRollPreviewSurface.cpp"
#include "SongEditor/PianoRoll/cocotone_PianoRollInteractionSurface.cpp"
#include "SongEditor/Transport/cocotone_TransportEmulator.cpp"
#include "SongEditor/Quantize/cocotone_QuantizeEngine.cpp"
#include "SongEditor/cocotone_SongEditorDataModel.cpp"
#include "SongEditor/cocotone_SongEditorDocument.cpp"
#include "SongEditor/cocotone_SongEditorCommand.cpp"
#include "SongEditor/cocotone_SongEditor.cpp"
